name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "23"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        
      - name: Deploy to VPS
        run: |
          ssh zulfi_fazhar12@34.136.71.182 << 'EOF'
            cd ~/ruangteknoid/RuangTeknoID/
            git pull origin main
            npm install
            npm run build
            sudo cp -rf ~/ruangteknoid/RuangTeknoID/dist/* /var/www/ruangteknoid.site/build/
            sudo systemctl restart nginx
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
